version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

#run docker-compose up --build to start docker container