version: '3.9'

services:
  backend:
    build: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MONGO_URI: ${MONGO_URI}
    expose:
      - "8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: "/api"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  app-network:
    driver: bridge
